when:
  - event: push
    branch: main

clone:
    git:
        image: woodpeckerci/plugin-git
        settings:
            tags: true
            partial: false
            depth: 0

steps:
  - name: build
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
        username:
            from_secret: DOCKER_USERNAME
        password:
            from_secret: DOCKER_TOKEN
        repo: docker.io/hrfee/jfa-go
        tags: unstable
        registry: docker.io
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        build_args:
          - BUILT_BY:
              from_secret: BUILT_BY
  - name: buildrone
    image: docker.io/python
    environment:
        BUILDRONE_KEY:
            from_secret: BUILDRONE_KEY
    commands:
      - wget https://builds.hrfee.pw/upload.py
      - pip install requests
      - python upload.py https://builds.hrfee.pw hrfee jfa-go --tag docker-unstable=true

