when:
  - event: tag
    branch: main

clone:
    git:
        image: woodpeckerci/plugin-git
        settings:
            tags: true
            partial: false
            depth: 0

steps:
  - name: precompile
    image: docker.io/hrfee/jfa-go-build-docker:latest
    environment:
        JFA_GO_SNAPSHOT: y
        JFA_GO_BUILT_BY:
            from_secret: BUILT_BY
    commands:
      - npm i
      - make precompile
      - go mod download
  - name: test
    image: docker.io/hrfee/jfa-go-build-docker:latest
    environment:
        JFA_GO_SNAPSHOT: y
        JFA_GO_BUILT_BY:
            from_secret: BUILT_BY
    commands:
      - make test
  - name: build
    image: docker.io/hrfee/jfa-go-build-docker:latest
    environment:
        JFA_GO_BUILT_BY:
            from_secret: BUILT_BY
        GITHUB_TOKEN:
            from_secret: GITHUB_TOKEN
    commands:
      - curl -sfL https://goreleaser.com/static/run > ../goreleaser
      - chmod +x ../goreleaser
      - ./scripts/version.sh ../goreleaser
  - name: deb-repo
    image: docker.io/hrfee/jfa-go-build-docker:latest
    environment:
        REPO_SSH_ID:
            from_secret: REPO_SSH_ID
    commands:
      - sh -c "echo \"$REPO_SSH_ID\" > /tmp/id_repo && chmod 600 /tmp/id_repo"
      - bash -c 'sftp -P 2022 -i /tmp/id_repo -o StrictHostKeyChecking=no root@apt.hrfee.dev:/repo/incoming <<< $"put dist/*.deb"'
      - bash -c 'ssh -i /tmp/id_repo root@apt.hrfee.dev -p 2022 "repo-process-deb trusty"'
      - bash -c 'ssh -i /tmp/id_repo root@apt.hrfee.dev -p 2022 "repo-process-deb trusty-unstable"'
      - bash -c 'ssh -i /tmp/id_repo root@apt.hrfee.dev -p 2022 "rm -f /repo/incoming/*.deb"'
  - name: buildrone
    image: docker.io/hrfee/jfa-go-build-docker:latest
    environment:
        BUILDRONE_KEY:
            from_secret: BUILDRONE_KEY
    commands:
      - wget https://builds.hrfee.pw/upload.py
      - bash -c 'python3 upload.py https://builds.hrfee.pw hrfee jfa-go --tag internal=true'
